### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by lmlr** [mccdaq/uldaq#4]
Hi,

I'm trying to use the python API with a USB-TEMP device. It works with the windows version (device shows up and I can read temperatures via Python) but the list returned by get_daq_device_inventory is empty when trying the same thing using Ubuntu 16.04 LTS.

The devices shows up using dmesg.

Any hints on what I'm doing wrong would be appreciated.

Edit:
I was able to communicate with the USB-TEMP following this guilde: https://www.mccdaq.com/TechTips/TechTip-9.aspx (using a raspberry pi)

Following this guide:
https://www.mccdaq.com/TechTips/TechTip-10.aspx
still does not work ("No DAQ devices found") on the Raspberry or the desktop Linux PC I tried it on.

**Comment by jeffreyg3** [comment]
Hello lmlr,

The UL for Linux does not provide support for the USB-TEMP at this time. For a complete list of supported devices:  https://www.mccdaq.com/PDFs/Manuals/Linux-hw.pdf

Though it may be included in a future release, I do not have a schedule at this time.

However, as you have discovered, it does work using the 3rd party driver.
http://kb.mccdaq.com/KnowledgebaseArticle50608.aspx

Best regards,
Jeff

**Comment by sbazaz** [comment]
Support for this device was added in version 1.1.0. Please make sure uldaq 1.1.0 or later is installed on your Linux system.

Below is the list of devices currently supported by the Universal Library for Linux
https://www.mccdaq.com/PDFs/Manuals/Linux-hw.pdf

**Comment by ztrayl3** [comment]
I am facing the same issue, as I am fully able to communicate between my USB-1608FS and my Raspberry Pi ZeroW through the examples in [this guide](https://www.mccdaq.com/TechTips/TechTip-9.aspx) but the python commands from [this guide](https://www.mccdaq.com/TechTips/TechTip-10.aspx) are giving me a "No DAQ devices found" error. 

Edit:
Turns out there are python test files AND python modules in "Linux_Drivers/USB/python" for use. These files do not import or rely on the uldaq module at all and may be the better option for interfacing certain devices with a Raspberry Pi

**Comment by jeffreyg3** [comment]
uldaq does not support the USB-1608FS but rather the USB-1608FS-Plus.
The library referred to in the above linked article (https://www.mccdaq.com/TechTips/TechTip-9.aspx) uses https://github.com/wjasper/Linux_Drivers.  
That library does include support for the USB-1608FS

Here is a link to the MCC devices supported with uldaq:
(https://www.mccdaq.com/PDFs/Manuals/Linux-hw.pdf)
